DECLARE
 stmt  varchar2(200);
 INDX_NAME  VARCHAR2(40) := ' ';
 INDX_COUNT NUMBER(4) :=0;
 COUNTER    NUMBER(4) :=1;
BEGIN
    SELECT COUNT(*) INTO INDX_COUNT
    FROM DBA_INDEXES
    WHERE TABLE_NAME LIKE 'PERS%';
    while COUNTER <= INDX_COUNT LOOP
       SELECT MIN(INDEX_NAME) INTO INDX_NAME
       FROM DBA_indexes
       WHERE INDEX_NAME > INDX_NAME and
       table_name like 'PERS%';
       stmt := 'ALTER INDEX ' || INDX_NAME ||
            ' REBUILD TABLESPACE SIDPERS_INDEX';
       DBMS_OUTPUT.PUT_LINE(STMT);
       EXECUTE IMMEDIATE stmt;
       COUNTER := COUNTER+1;
    END LOOP;
END;
/
