  ALTER PROFILE DEFAULT
  LIMIT   SESSIONS_PER_USER         UNLIMITED
  CPU_PER_SESSION   UNLIMITED
  CPU_PER_CALL    UNLIMITED
  CONNECT_TIME    UNLIMITED
  LOGICAL_READS_PER_SESSION DEFAULT
  LOGICAL_READS_PER_CALL    DEFAULT
  IDLE_TIME     UNLIMITED
  FAILED_LOGIN_ATTEMPTS       UNLIMITED
/
