CREATE OR REPLACE PROCEDURE CALL_BIG(parm1 number)
AS
BEGIN
  		FOR I IN 1..parm1 LOOP
      		IF I BETWEEN 1 AND 1999 THEN
         		INSERT INTO scott.BIGPROC VALUES(I,'ONE THOUSAND');
      		ELSIF I BETWEEN 2000 AND 5000 THEN
        		 INSERT INTO scott.BIGPROC VALUES(I,'BET 2K AND 5K');
      		ELSE
         		INSERT INTO scott.BIGPROC VALUES(I,NULL);
      		END IF;
      		IF MOD(I,1000) = 0 THEN COMMIT;
      		END IF;
  		END LOOP;
END CALL_BIG;
/
