CREATE TABLE DATETIME_SAMPLES
(DT     DATE,
 TS      TIMESTAMP(3),
 TS2     TIMESTAMP,
 TST2    TIMESTAMP(3) WITH TIME ZONE,
 TSLTZ   TIMESTAMP WITH LOCAL TIME ZONE,
 LONG_DURATION  INTERVAL YEAR(4) TO MONTH,
 SHORT_DURATION INTERVAL DAY(3) TO SECOND(2))
/
