CREATE CONTROLFILE REUSE DATABASE orcl
LOGFILE GROUP 1 ('c:\oracle\orclLOG1A.log','orclLOG1B.log') SIZE 100m,
        GROUP 2 ('c:\oracle\orclLOG2A.log','orclLOG2B.log') SIZE 100m RESETLOGS
DATAFILE 'C:\ORACLE\PRODUCT\10.1.0\ORADATA\ORCL\SYSTEM01.DBF',
         'C:\ORACLE\PRODUCT\10.1.0\ORADATA\ORCL\UNDOTBS01.DBF',
         'C:\ORACLE\PRODUCT\10.1.0\ORADATA\ORCL\SYSAUX01.DBF',
         'C:\WINDOWS\SYSTEM32\SIDERISUSERS.DBF',
         'C:\ORACLE\PRODUCT\10.1.0\ORADATA\ORCL\EXAMPLE01.DBF',
         'C:\ORACLE\RMAN.DBF',
         'C:\ORACLE\ORCL\DATAFILE\O1_MF_JERRY_1CJW7D1Y_.DBF',
         'C:\ORACLE\ORCL\DATAFILE\O1_MF_USERS2_1CJZD8TV_.DBF',
         'C:\ORACLE\USERS1.DBF',
         'C:\ORACLE\TOOLS.DBF',
         'C:\TEMP\USER_DATA.DBF',
         'C:\ORACLE\JERDATA.DBF' 
;
