INSERT INTO dept VALUES (
   10, 'Finance', 1);
INSERT INTO dept VALUES (
   31, 'Sales', 1);
INSERT INTO dept VALUES (
   32, 'Sales', 2);
INSERT INTO dept VALUES (
   33, 'Sales', 3);
INSERT INTO dept VALUES (
   34, 'Sales', 4);
INSERT INTO dept VALUES (
   35, 'Sales', 5);
INSERT INTO dept VALUES (
   41, 'Operations', 1);
INSERT INTO dept VALUES (
   42, 'Operations', 2);
INSERT INTO dept VALUES (
   43, 'Operations', 3);
INSERT INTO dept VALUES (
   44, 'Operations', 4);
INSERT INTO dept VALUES (
   45, 'Operations', 5);
INSERT INTO dept VALUES (
   50, 'Administration', 1);
COMMIT;
