INSERT INTO students VALUES
  (StudentObj(student_sequence.NEXTVAL,'SCOTT','SMITH','COMPUTER SCIENCE',0),
   AddressObj('100 Main St','East Brunswick','CA',91234));
INSERT INTO students VALUES
  (StudentObj(student_sequence.NEXTVAL,'Margret','Jacoby','History',0),
   AddressObj('350 Sorority Row','HOUSTON','TX',77057));
INSERT INTO students VALUES
  (StudentObj(student_sequence.NEXTVAL,'BETH','TURNER','MATH',0),
   AddressObj('677 HEAVEN','BOSTON','MA',45747));