/*  lab4 answers for 4 - 8  */


/* #4  goodinsrt.sql  */
/*  INSERT INTO APPLICANT WHERE NEW TEMPID IS NOT IN STAFF TABLE */

INSERT INTO APPLICANT  -- 4A
SELECT 400, 'RICHARD','103 RIVA RIDGE',18,'GIVE RAISE'
FROM DUAL WHERE 400 NOT IN
(SELECT ID FROM STAFF);