SELECT EMPNO,ENAME,JOB,SAL,E.DEPTNO,DNAME,
SAL * 12 +NVL(COMM,0)
  FROM EMP E,DEPT D
  WHERE E.DEPTNO = D.DEPTNO AND
  SAL* 12 + NVL(COMM,0) BETWEEN 15000 AND 30000 AND
  HIREDATE < '01-JAN-99' AND JOB = 'SALESMAN'
/
