SELECT P.SSN_SM, P.NAME_IND,P.YR_MO_LAST_PHYS_EX,
           U.UNAME,
           S.CUM_RET_PT,
           SP.PAY_GR, SP.NBR_EXEMPT
FROM PERS_PERSON_TBL P, PERS_SVCMBR_TBL S,
     PERS_UNIT_TBL U, PERS_SVCMBR_PAY_TBL SP
WHERE P.SSN_SM = S.SSN_SM AND P.REC_PREC = S.REC_PREC
   AND S.UPC = U.UPC 
   AND S.MPC=SP.MPC AND S.ASG_SEQ_NBR=SP.ASG_SEQ_NBR
/
