insert into pers_svcmbr_tbl (MPC,ASG_SEQ_NBR,SSN_SM,REC_PREC,REC_STAT,DATE_REC_STAT)
VALUES ('E',30000,'123456780','20070327','K'
MPC                                                                      NOT NULL VARCHAR2(1)
ASG_SEQ_NBR                                                              NOT NULL NUMBER(6)
SSN_SM                                                                   NOT NULL VARCHAR2(9)
REC_PREC                                                                 NOT NULL VARCHAR2(8)
REC_STAT                                                                 NOT NULL VARCHAR2(1)
DATE_REC_STAT                                                            NOT NULL DATE                                                          NOT NULL DATE
/
