CREATE TABLE PERSON_IOT
(SSN_SM		VARCHAR2(9) NOT NULL,
  REC_PREC		VARCHAR2(8) NOT NULL,
  AREAX 		VARCHAR2(3) NOT NULL,
  NAME_IND   VARCHAR2(27)	NOT NULL,
  TYPE      VARCHAR2(1) NOT NULL,
  STATES_US  CHAR(2),
  DOB        DATE,
  APFT_RESULT CHAR(1),
  APFT_SCORE  NUMBER(3),
   CONSTRAINT  SOLDIER_PK PRIMARY KEY (SSN_SM,REC_PREC)
)
ORGANIZATION INDEX TABLESPACE TOOLS
PCTTHRESHOLD  20
INCLUDING AREAX,NAME_IND,TYPE,STATES_US,DOB,APFT_RESULT,APFT_SCORE
OVERFLOW TABLESPACE USER_DATA
/
