SELECT p.NAME_IND,rp.REC_PREC,r.REC_STAT,
a.AERO_DESC,I.IPAY_NBR,i.IPAY_DESC,MAX(sp.DATE_IPAY_NBR_ONE)
FROM SIDPERS.PERS_PERSON_TBL p, 
SIDPERS.PERS_SVCMBR_PAY_TBL sp, 
SIDPERS.PERS_AERO_CODE_TBL a,
SIDPERS.PERS_IPAY_CODE_TBL i,
SIDPERS.PERS_RECSTAT_CODE_TBL r,
SIDPERS.PERS_PERSON_TBL rp 
WHERE ((sp.ASG_SEQ_NBR|| sp.MPC) = (p.ASG_SEQ_NBR|| p.MPC)) AND
 (sp.CURR_AERO_RT <> 'Z' AND sp.CURR_AERO_RT <> 'W') AND
 (sp.CURR_AERO_RT = a.CURR_AERO_RT) AND 
(sp.IPAY_NBR_ONE = i.IPAY_NBR) AND 
((REC_STAT <> 'K' OR REC_STAT <> 'M') AND 
rp.REC_PREC = 99999999 AND 
((REC_STAT = 'G') or (REC_STAT = 'H') or (REC_STAT = 'T')) )
group by p.NAME_IND, rp.REC_PREC, a.AERO_DESC, I.IPAY_NBR, i.IPAY_DESC
ORDER BY (p.NAME_IND)
/
